/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://localhost:8080/v1";

}
