/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron;

import com.api.dkron.controllers.*;
import com.api.dkron.http.client.HttpClient;

public class DkronRESTAPIClient {
    /**
     * Singleton access to Default controller
     * @return	Returns the DefaultController instance 
     */
    public DefaultController getDefault() {
        return DefaultController.getInstance();
    }

    /**
     * Singleton access to Jobs controller
     * @return	Returns the JobsController instance 
     */
    public JobsController getJobs() {
        return JobsController.getInstance();
    }

    /**
     * Singleton access to Members controller
     * @return	Returns the MembersController instance 
     */
    public MembersController getMembers() {
        return MembersController.getInstance();
    }

    /**
     * Singleton access to Executions controller
     * @return	Returns the ExecutionsController instance 
     */
    public ExecutionsController getExecutions() {
        return ExecutionsController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public DkronRESTAPIClient() {	
	}

}