/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron;

import com.api.dkron.resources.BaseResource;
import com.api.dkron.resources.MemberResource;
import com.api.dkron.resources.JobResource;
import com.api.dkron.resources.DefaultResource;
import com.api.dkron.resources.ExecutionResource;
import com.api.dkron.http.client.HttpClient;

public class DkronRESTAPIClient {
    /**
     * Singleton access to Default controller
     * @return	Returns the DefaultResource instance 
     */
    public DefaultResource getDefault() {
        return DefaultResource.getInstance();
    }

    /**
     * Singleton access to Jobs controller
     * @return	Returns the JobResource instance 
     */
    public JobResource getJobs() {
        return JobResource.getInstance();
    }

    /**
     * Singleton access to Members controller
     * @return	Returns the MemberResource instance 
     */
    public MemberResource getMembers() {
        return MemberResource.getInstance();
    }

    /**
     * Singleton access to Executions controller
     * @return	Returns the ExecutionResource instance 
     */
    public ExecutionResource getExecutions() {
        return ExecutionResource.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseResource.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseResource.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public DkronRESTAPIClient() {	
	}

}