/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron.models;

import com.api.dkron.DateAndTimeDeserialize;
import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

public class Execution 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5070018395204489837L;
    private Date finishedAt;
    private String jobName;
    private String nodeName;
    private String output;
    private Date startedAt;
    private Boolean success;
    /** GETTER
     * when the execution finished running
     */
    @JsonGetter("finished_at")
    public Date getFinishedAt ( ) { 
        return this.finishedAt;
    }
    
    /** SETTER
     * when the execution finished running
     */
    @JsonSetter("finished_at")
    @JsonDeserialize(using=DateAndTimeDeserialize.class)
    public void setFinishedAt (Date value) { 
        this.finishedAt = value;
    }
 
    /** GETTER
     * job name
     */
    @JsonGetter("job_name")
    public String getJobName ( ) { 
        return this.jobName;
    }
    
    /** SETTER
     * job name
     */
    @JsonSetter("job_name")
    public void setJobName (String value) { 
        this.jobName = value;
    }
 
    /** GETTER
     * name of the node that executed the command
     */
    @JsonGetter("node_name")
    public String getNodeName ( ) { 
        return this.nodeName;
    }
    
    /** SETTER
     * name of the node that executed the command
     */
    @JsonSetter("node_name")
    public void setNodeName (String value) { 
        this.nodeName = value;
    }
 
    /** GETTER
     * partial output of the command execution
     */
    @JsonGetter("output")
    public String getOutput ( ) { 
        return this.output;
    }
    
    /** SETTER
     * partial output of the command execution
     */
    @JsonSetter("output")
    public void setOutput (String value) { 
        this.output = value;
    }
 
    /** GETTER
     * start time of the execution
     */
    @JsonGetter("started_at")
    public Date getStartedAt ( ) { 
        return this.startedAt;
    }
    
    /** SETTER
     * start time of the execution
     */
    @JsonSetter("started_at")
    @JsonDeserialize(using=DateAndTimeDeserialize.class)
    public void setStartedAt (Date value) { 
        this.startedAt = value;
    }
 
    /** GETTER
     * the execution run successfuly
     */
    @JsonGetter("success")
    public Boolean getSuccess ( ) { 
        return this.success;
    }
    
    /** SETTER
     * the execution run successfuly
     */
    @JsonSetter("success")
    public void setSuccess (Boolean value) { 
        this.success = value;
    }
 
}
 