/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron.models;

import java.util.*;

public class ExecutionBuilder {
    //the instance to build
    private Execution execution;

    /**
     * Default constructor to initialize the instance
     */
    public ExecutionBuilder() {
        execution = new Execution();
    }

    /**
     * when the execution finished running
     */
    public ExecutionBuilder finishedAt(Date finishedAt) {
        execution.setFinishedAt(finishedAt);
        return this;
    }

    /**
     * job name
     */
    public ExecutionBuilder jobName(String jobName) {
        execution.setJobName(jobName);
        return this;
    }

    /**
     * name of the node that executed the command
     */
    public ExecutionBuilder nodeName(String nodeName) {
        execution.setNodeName(nodeName);
        return this;
    }

    /**
     * partial output of the command execution
     */
    public ExecutionBuilder output(String output) {
        execution.setOutput(output);
        return this;
    }

    /**
     * start time of the execution
     */
    public ExecutionBuilder startedAt(Date startedAt) {
        execution.setStartedAt(startedAt);
        return this;
    }

    /**
     * the execution run successfuly
     */
    public ExecutionBuilder success(Boolean success) {
        execution.setSuccess(success);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Execution build() {
        return execution;
    }
}