/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Job 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5029181494628764580L;
    private String command;
    private String name;
    private String schedule;
    private String dependentJobs;
    private Boolean disabled;
    private Integer errorCount;
    private Date lastError;
    private Date lastSuccess;
    private String owner;
    private String ownerEmail;
    private String parentJob;
    private Integer retries;
    private Boolean shell;
    private Integer successCount;
    private Object tags;
    /** GETTER
     * Command to run.
     */
    @JsonGetter("command")
    public String getCommand ( ) { 
        return this.command;
    }
    
    /** SETTER
     * Command to run.
     */
    @JsonSetter("command")
    public void setCommand (String value) { 
        this.command = value;
    }
 
    /** GETTER
     * Name for the job.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Name for the job.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Cron expression for the job.
     */
    @JsonGetter("schedule")
    public String getSchedule ( ) { 
        return this.schedule;
    }
    
    /** SETTER
     * Cron expression for the job.
     */
    @JsonSetter("schedule")
    public void setSchedule (String value) { 
        this.schedule = value;
    }
 
    /** GETTER
     * Array containing the jobs that depends on this one
     */
    @JsonGetter("dependent_jobs")
    public String getDependentJobs ( ) { 
        return this.dependentJobs;
    }
    
    /** SETTER
     * Array containing the jobs that depends on this one
     */
    @JsonSetter("dependent_jobs")
    public void setDependentJobs (String value) { 
        this.dependentJobs = value;
    }
 
    /** GETTER
     * Disabled state of the job
     */
    @JsonGetter("disabled")
    public Boolean getDisabled ( ) { 
        return this.disabled;
    }
    
    /** SETTER
     * Disabled state of the job
     */
    @JsonSetter("disabled")
    public void setDisabled (Boolean value) { 
        this.disabled = value;
    }
 
    /** GETTER
     * Number of failed executions
     */
    @JsonGetter("error_count")
    public Integer getErrorCount ( ) { 
        return this.errorCount;
    }
    
    /** SETTER
     * Number of failed executions
     */
    @JsonSetter("error_count")
    public void setErrorCount (Integer value) { 
        this.errorCount = value;
    }
 
    /** GETTER
     * Last time this job failed
     */
    @JsonGetter("last_error")
    public Date getLastError ( ) { 
        return this.lastError;
    }
    
    /** SETTER
     * Last time this job failed
     */
    @JsonSetter("last_error")
    public void setLastError (Date value) { 
        this.lastError = value;
    }
 
    /** GETTER
     * Last time this job executed successfully
     */
    @JsonGetter("last_success")
    public Date getLastSuccess ( ) { 
        return this.lastSuccess;
    }
    
    /** SETTER
     * Last time this job executed successfully
     */
    @JsonSetter("last_success")
    public void setLastSuccess (Date value) { 
        this.lastSuccess = value;
    }
 
    /** GETTER
     * Owner of the job
     */
    @JsonGetter("owner")
    public String getOwner ( ) { 
        return this.owner;
    }
    
    /** SETTER
     * Owner of the job
     */
    @JsonSetter("owner")
    public void setOwner (String value) { 
        this.owner = value;
    }
 
    /** GETTER
     * Email of the owner
     */
    @JsonGetter("owner_email")
    public String getOwnerEmail ( ) { 
        return this.ownerEmail;
    }
    
    /** SETTER
     * Email of the owner
     */
    @JsonSetter("owner_email")
    public void setOwnerEmail (String value) { 
        this.ownerEmail = value;
    }
 
    /** GETTER
     * The name/id of the job that will trigger the execution of this job
     */
    @JsonGetter("parent_job")
    public String getParentJob ( ) { 
        return this.parentJob;
    }
    
    /** SETTER
     * The name/id of the job that will trigger the execution of this job
     */
    @JsonSetter("parent_job")
    public void setParentJob (String value) { 
        this.parentJob = value;
    }
 
    /** GETTER
     * Number of times to retry a failed job execution
     */
    @JsonGetter("retries")
    public Integer getRetries ( ) { 
        return this.retries;
    }
    
    /** SETTER
     * Number of times to retry a failed job execution
     */
    @JsonSetter("retries")
    public void setRetries (Integer value) { 
        this.retries = value;
    }
 
    /** GETTER
     * Use shell to run the command
     */
    @JsonGetter("shell")
    public Boolean getShell ( ) { 
        return this.shell;
    }
    
    /** SETTER
     * Use shell to run the command
     */
    @JsonSetter("shell")
    public void setShell (Boolean value) { 
        this.shell = value;
    }
 
    /** GETTER
     * Number of successful executions
     */
    @JsonGetter("success_count")
    public Integer getSuccessCount ( ) { 
        return this.successCount;
    }
    
    /** SETTER
     * Number of successful executions
     */
    @JsonSetter("success_count")
    public void setSuccessCount (Integer value) { 
        this.successCount = value;
    }
 
    /** GETTER
     * Tags asociated with this node
     */
    @JsonGetter("tags")
    public Object getTags ( ) { 
        return this.tags;
    }
    
    /** SETTER
     * Tags asociated with this node
     */
    @JsonSetter("tags")
    public void setTags (Object value) { 
        this.tags = value;
    }
 
}
 