/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Member 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5245152491207799815L;
    private String addr;
    private Integer delegateCur;
    private Integer delegateMax;
    private Integer delegateMin;
    private String name;
    private Integer port;
    private Integer protocolCur;
    private Integer protocolMax;
    private Integer protocolMin;
    private Integer status;
    private Object tags;
    /** GETTER
     * IP Address
     */
    @JsonGetter("Addr")
    public String getAddr ( ) { 
        return this.addr;
    }
    
    /** SETTER
     * IP Address
     */
    @JsonSetter("Addr")
    public void setAddr (String value) { 
        this.addr = value;
    }
 
    /** GETTER
     * Serf delegate protocol minimum version this node can understand or speak
     */
    @JsonGetter("DelegateCur")
    public Integer getDelegateCur ( ) { 
        return this.delegateCur;
    }
    
    /** SETTER
     * Serf delegate protocol minimum version this node can understand or speak
     */
    @JsonSetter("DelegateCur")
    public void setDelegateCur (Integer value) { 
        this.delegateCur = value;
    }
 
    /** GETTER
     * Serf delegate protocol minimum version this node can understand or speak
     */
    @JsonGetter("DelegateMax")
    public Integer getDelegateMax ( ) { 
        return this.delegateMax;
    }
    
    /** SETTER
     * Serf delegate protocol minimum version this node can understand or speak
     */
    @JsonSetter("DelegateMax")
    public void setDelegateMax (Integer value) { 
        this.delegateMax = value;
    }
 
    /** GETTER
     * Serf delegate protocol minimum version this node can understand or speak
     */
    @JsonGetter("DelegateMin")
    public Integer getDelegateMin ( ) { 
        return this.delegateMin;
    }
    
    /** SETTER
     * Serf delegate protocol minimum version this node can understand or speak
     */
    @JsonSetter("DelegateMin")
    public void setDelegateMin (Integer value) { 
        this.delegateMin = value;
    }
 
    /** GETTER
     * Node name
     */
    @JsonGetter("Name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * Node name
     */
    @JsonSetter("Name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * Port number
     */
    @JsonGetter("Port")
    public Integer getPort ( ) { 
        return this.port;
    }
    
    /** SETTER
     * Port number
     */
    @JsonSetter("Port")
    public void setPort (Integer value) { 
        this.port = value;
    }
 
    /** GETTER
     * Serf protocol current version this node can understand or speak
     */
    @JsonGetter("ProtocolCur")
    public Integer getProtocolCur ( ) { 
        return this.protocolCur;
    }
    
    /** SETTER
     * Serf protocol current version this node can understand or speak
     */
    @JsonSetter("ProtocolCur")
    public void setProtocolCur (Integer value) { 
        this.protocolCur = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ProtocolMax")
    public Integer getProtocolMax ( ) { 
        return this.protocolMax;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ProtocolMax")
    public void setProtocolMax (Integer value) { 
        this.protocolMax = value;
    }
 
    /** GETTER
     * Serf protocol minimum version this node can understand or speak
     */
    @JsonGetter("ProtocolMin")
    public Integer getProtocolMin ( ) { 
        return this.protocolMin;
    }
    
    /** SETTER
     * Serf protocol minimum version this node can understand or speak
     */
    @JsonSetter("ProtocolMin")
    public void setProtocolMin (Integer value) { 
        this.protocolMin = value;
    }
 
    /** GETTER
     * The serf status of the node see: https://godoc.org/github.com/hashicorp/serf/serf#MemberStatus
     */
    @JsonGetter("Status")
    public Integer getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * The serf status of the node see: https://godoc.org/github.com/hashicorp/serf/serf#MemberStatus
     */
    @JsonSetter("Status")
    public void setStatus (Integer value) { 
        this.status = value;
    }
 
    /** GETTER
     * Tags asociated with this node
     */
    @JsonGetter("Tags")
    public Object getTags ( ) { 
        return this.tags;
    }
    
    /** SETTER
     * Tags asociated with this node
     */
    @JsonSetter("Tags")
    public void setTags (Object value) { 
        this.tags = value;
    }
 
}
 