/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron.models;

import java.util.*;

public class MemberBuilder {
    //the instance to build
    private Member member;

    /**
     * Default constructor to initialize the instance
     */
    public MemberBuilder() {
        member = new Member();
    }

    /**
     * IP Address
     */
    public MemberBuilder addr(String addr) {
        member.setAddr(addr);
        return this;
    }

    /**
     * Serf delegate protocol minimum version this node can understand or speak
     */
    public MemberBuilder delegateCur(Integer delegateCur) {
        member.setDelegateCur(delegateCur);
        return this;
    }

    /**
     * Serf delegate protocol minimum version this node can understand or speak
     */
    public MemberBuilder delegateMax(Integer delegateMax) {
        member.setDelegateMax(delegateMax);
        return this;
    }

    /**
     * Serf delegate protocol minimum version this node can understand or speak
     */
    public MemberBuilder delegateMin(Integer delegateMin) {
        member.setDelegateMin(delegateMin);
        return this;
    }

    /**
     * Node name
     */
    public MemberBuilder name(String name) {
        member.setName(name);
        return this;
    }

    /**
     * Port number
     */
    public MemberBuilder port(Integer port) {
        member.setPort(port);
        return this;
    }

    /**
     * Serf protocol current version this node can understand or speak
     */
    public MemberBuilder protocolCur(Integer protocolCur) {
        member.setProtocolCur(protocolCur);
        return this;
    }

    public MemberBuilder protocolMax(Integer protocolMax) {
        member.setProtocolMax(protocolMax);
        return this;
    }

    /**
     * Serf protocol minimum version this node can understand or speak
     */
    public MemberBuilder protocolMin(Integer protocolMin) {
        member.setProtocolMin(protocolMin);
        return this;
    }

    /**
     * The serf status of the node see: https://godoc.org/github.com/hashicorp/serf/serf#MemberStatus
     */
    public MemberBuilder status(Integer status) {
        member.setStatus(status);
        return this;
    }

    /**
     * Tags asociated with this node
     */
    public MemberBuilder tags(Object tags) {
        member.setTags(tags);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Member build() {
        return member;
    }
}