/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron.models;

import java.util.*;

public class StatusBuilder {
    //the instance to build
    private Status status;

    /**
     * Default constructor to initialize the instance
     */
    public StatusBuilder() {
        status = new Status();
    }

    /**
     * Node basic details
     */
    public StatusBuilder agent(Object agent) {
        status.setAgent(agent);
        return this;
    }

    /**
     * Serf status
     */
    public StatusBuilder serf(Object serf) {
        status.setSerf(serf);
        return this;
    }

    /**
     * Tags asociated with this node
     */
    public StatusBuilder tags(Object tags) {
        status.setTags(tags);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Status build() {
        return status;
    }
}