/*
 * DkronRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.api.dkron.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Status 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5568508531763044553L;
    private Object agent;
    private Object serf;
    private Object tags;
    /** GETTER
     * Node basic details
     */
    @JsonGetter("agent")
    public Object getAgent ( ) { 
        return this.agent;
    }
    
    /** SETTER
     * Node basic details
     */
    @JsonSetter("agent")
    public void setAgent (Object value) { 
        this.agent = value;
    }
 
    /** GETTER
     * Serf status
     */
    @JsonGetter("serf")
    public Object getSerf ( ) { 
        return this.serf;
    }
    
    /** SETTER
     * Serf status
     */
    @JsonSetter("serf")
    public void setSerf (Object value) { 
        this.serf = value;
    }
 
    /** GETTER
     * Tags asociated with this node
     */
    @JsonGetter("tags")
    public Object getTags ( ) { 
        return this.tags;
    }
    
    /** SETTER
     * Tags asociated with this node
     */
    @JsonSetter("tags")
    public void setTags (Object value) { 
        this.tags = value;
    }
 
}
 